stages:
  - build
  - deploy
.deploy_default:
  variables:
    GIT_STRATEGY: clone
    DEPLOY_PATH: /blog
  tags:
    - hexo
.deploy_base:
  extends:
    - .deploy_default
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
# [构建镜像](# 构建镜像)
build_hexo:
  stage: build
  extends:
    - .deploy_base
  variables:
    IMAGE_NAME: hexo
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+/
  script:
    - cd docker
    - docker build -t $IMAGE_NAME:$CI_COMMIT_TAG .
deploy_hexo:
  extends:
    - .deploy_base
  stage: deploy
  script:
    - rsync -avz --delete-after --exclude 'docker' --exclude '.git' --exclude 'node_modules' . ${DEPLOY_PATH}/hexo_blog
    - rsync -avz --delete-after docker/docker-compose.yml ${DEPLOY_PATH}/hexo_docker/docker-compose.yml

